### ISSUE TITLE
UPD5: Closed issue for reopen with bounty

### ISSUE THREAD

**Issue by anna07test** [anna07test-org-in-SOB/anna07test-repo1-in-SOB#5]

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Tokens: SNT: 59.00
Contract address: [0x20a3788a101fbf1b02355b664e71c8004d034c33](https://ropsten.etherscan.io/address/0x20a3788a101fbf1b02355b664e71c8004d034c33)
![QR Code](https://openbounty.status.im:444/qr/anna07test-org-in-SOB/anna07test-repo1-in-SOB/bounty/5/2362f9722c61fd3d3338c4db5bcdf9006fe1e64b2ea0fc08ee3f095575c5404c/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://openbounty.status.im:444](https://openbounty.status.im:444) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
